# Generated by Django 4.1 on 2022-10-07 22:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=32)),
                ('receptor', models.CharField(max_length=32)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('emisorid', models.IntegerField()),
                ('receptorid', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
