# Generated by Django 4.1 on 2022-10-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='emisorid',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receptorid',
        ),
    ]
