# Generated by Django 4.1 on 2022-10-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajeria', '0002_remove_messages_emisorid_remove_messages_receptorid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
